k8s_yaml('serve.yaml')

docker_build('k8cher-web', '.',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'package-lock.json']),
    # Map the local source code into the container under /app
    sync('.', '/app'),
  ])

k8s_resource('k8cher-web', port_forwards=3000)
